# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('is_infected', models.BooleanField()),
                ('count_reports', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Survivor',
                'verbose_name_plural': 'Survivors',
            },
        ),
    ]
