# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_auto_20180706_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='survivor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restApi.Survivor', verbose_name='Survivor'),
        ),
    ]
