# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0005_auto_20180706_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField()),
                ('inventories', models.ManyToManyField(to='restApi.Inventory', verbose_name='Inventories')),
            ],
            options={
                'verbose_name': 'Inventory_Item',
                'verbose_name_plural': 'Inventories_Items',
            },
        ),
    ]
