# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0006_inventory_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_items',
            name='survivor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restApi.Survivor', verbose_name='Survivor'),
            preserve_default=False,
        ),
    ]
