# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0007_inventory_items_survivor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_items',
            name='survivor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restApi.Survivor', verbose_name='Survivor'),
        ),
    ]
