# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0009_auto_20180707_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_items',
            name='survivor_id',
            field=models.IntegerField(default=0),
        ),
    ]
